//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Scripts/Inputs/PlayerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControl"",
    ""maps"": [
        {
            ""name"": ""PlayerGraber"",
            ""id"": ""6c0087b8-e6c7-4575-9490-bd3dd99d1c21"",
            ""actions"": [
                {
                    ""name"": ""ClickPlayer"",
                    ""type"": ""Button"",
                    ""id"": ""6fce667f-0cc3-41f7-8008-395b67ca5e39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1d4bace-cb89-4cf8-9ec2-11f26100efeb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickPlayer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerGraber
        m_PlayerGraber = asset.FindActionMap("PlayerGraber", throwIfNotFound: true);
        m_PlayerGraber_ClickPlayer = m_PlayerGraber.FindAction("ClickPlayer", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerGraber
    private readonly InputActionMap m_PlayerGraber;
    private List<IPlayerGraberActions> m_PlayerGraberActionsCallbackInterfaces = new List<IPlayerGraberActions>();
    private readonly InputAction m_PlayerGraber_ClickPlayer;
    public struct PlayerGraberActions
    {
        private @PlayerControl m_Wrapper;
        public PlayerGraberActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickPlayer => m_Wrapper.m_PlayerGraber_ClickPlayer;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGraber; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGraberActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerGraberActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerGraberActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerGraberActionsCallbackInterfaces.Add(instance);
            @ClickPlayer.started += instance.OnClickPlayer;
            @ClickPlayer.performed += instance.OnClickPlayer;
            @ClickPlayer.canceled += instance.OnClickPlayer;
        }

        private void UnregisterCallbacks(IPlayerGraberActions instance)
        {
            @ClickPlayer.started -= instance.OnClickPlayer;
            @ClickPlayer.performed -= instance.OnClickPlayer;
            @ClickPlayer.canceled -= instance.OnClickPlayer;
        }

        public void RemoveCallbacks(IPlayerGraberActions instance)
        {
            if (m_Wrapper.m_PlayerGraberActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerGraberActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerGraberActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerGraberActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerGraberActions @PlayerGraber => new PlayerGraberActions(this);
    public interface IPlayerGraberActions
    {
        void OnClickPlayer(InputAction.CallbackContext context);
    }
}
